codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "40...80"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true

    patch:
      default:
        target: 70%
        threshold: 0%
        only_pulls: true
        informational: true

flags:
  app:
    paths:
      - app/src/main/
  core-common:
    paths:
      - core/common/src/main/
  core-network:
    paths:
      - core/network/src/main/
  core-ui:
    paths:
      - core/ui/src/main/
  feature-stocklist:
    paths:
      - feature/stocklist/src/main/

comment:
  layout: "reach,diff,files"
  behavior: default
  require_changes: false

ignore:
  - "**/build/**"
  - "**/src/test/**"
  - "**/src/androidTest/**"
